### ISSUE TITLE
Add support for `sudo`

### ISSUE THREAD

**Issue by liamg** [liamg/peridot#3]
Modules need to be able to request `sudo` access for individual scripts.

Something like:

```
scripts:
  install:
    sudo: true
    command: ./install.sh
```
